baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

DefaultContentLanguage = "en"
canonifyurls = true
metaDataFormat = "toml"
theme = "hugo-bootstrap-premium"

uglyurls = true

[mediaTypes]
[mediaTypes."text/properties"]
suffix = "properties"

[outputFormats.eclssetup]
mediaType = "text/properties"
#baseName = "eclssetup"
isPlainText = true